### ISSUE TITLE
Wrong name of behr_variables

### ISSUE THREAD

**Issue by zxdawn** [CohenBerkeleyLab/BEHR-core#7]
https://github.com/CohenBerkeleyLab/BEHR-core/blob/408dc1b794f9c469ebf4a75f4336df7b818db7f7/Read_Data/read_main.m#L394

Becasue 'GLOBETerpres' has been changed to 'GLOBETerrainHeight' in BEHR_main_one_day.m,  behr_variables in read_main.m should be modified.
https://github.com/CohenBerkeleyLab/BEHR-core/blob/a60133ecc673ad4b6aa24adce2fc69d35ea9048e/BEHR_Main/BEHR_main_one_day.m#L155

**Comment by behr-github** [comment]
Fixed in 427d9f991acdf4d47db56009ce5b81fef2013d03
